# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Package

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [2, 3]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install tox

      - name: Cache tox environments
        uses: actions/cache@v2
        with:
          path: .tox
          # setup.cfg, pyproject.toml, etc. contain information that 
          # may impact the tox environment.
          key: ${{ runner.os }}-${{ matrix.python }}-tox-${{ hashFiles('tox.ini', 'setup.py', 'pyproject.toml', 'src/PyCoD/__init__.py') }}
      
      - name: Run Tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py
